import os

SOURCE = "vault_chapters/AI"
OUTPUT = "vault_books/AI_Testing_Handbook.md"

chapters = []

ORDER = [
    "exploratory_testing.md",
    "bug_types.md",
    "drift_and_failure_modes.md"
]

book = []

book.append("# AI Testing Handbook\n")
book.append("Generated by Pipe Dreams\n")
book.append("\n---\n")

book.append("""
# Introduction

This handbook is a collection of observations,
failure modes, testing techniques, and practical
methods for evaluating large language models.

The goal is not merely to use AI systems, but
to understand how they behave under pressure,
constraints, ambiguity, and extended interaction.

---
""")

for filename in ORDER:

    path = os.path.join(SOURCE, filename)

    if not os.path.exists(path):
        continue

    with open(path, "r", encoding="utf-8") as f:
        book.append(f.read())
        book.append("\n\n---\n\n")

book.append("""
# Conclusion

The purpose of exploratory testing is not to
break systems for its own sake.

The purpose is to understand them.

By observing bug types, drift patterns,
failure modes, and stress responses,
we gain a clearer picture of how modern
AI systems behave and where their limits lie.

This knowledge allows builders,
researchers, and users to create
more reliable systems in the future.
""")

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("\n".join(book))

print()
print("Created:", OUTPUT)
print()
