import os
import re

SOURCE = "vault_refined/AI"
DEST = "vault_chapters/AI"

os.makedirs(DEST, exist_ok=True)

for filename in os.listdir(SOURCE):

    if not filename.endswith(".md"):
        continue

    path = os.path.join(SOURCE, filename)

    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    chapter_title = (
        filename
        .replace(".md", "")
        .replace("_", " ")
        .title()
    )

    sections = re.split(
        r'\n\s*# .*?\.md\s*\n',
        text
    )

    cleaned = []

    for section in sections:

        section = section.strip()

        if len(section) < 50:
            continue

        section = section.replace("# Ai Note", "")
        section = section.replace("# AI Note", "")

        lines = [
            line.strip()
            for line in section.splitlines()
            if line.strip()
        ]

        if not lines:
            continue

        section_title = lines[0]

        section_body = "\n".join(lines[1:])

        cleaned.append(
            f"\n## {section_title}\n\n{section_body}\n"
        )

    output = (
        f"# {chapter_title}\n\n"
        f"Generated by Pipe Dreams Chapter Builder\n\n"
        + "\n".join(cleaned)
    )

    outfile = os.path.join(
        DEST,
        filename
    )

    with open(
        outfile,
        "w",
        encoding="utf-8"
    ) as f:
        f.write(output)

    print("Built:", outfile)

print()
print("Chapter build complete.")
